const restList = [
  {
    name: "Domino's Pizza",
    cloudinaryImageId: "hbeqc0r6ifvqiuychft2",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.4,
    slaString: "25 mins",
  },
  {
    name: "Baskin Robbins",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts", "Ice Cream"],
    avgRating: 4.2,
    slaString: "35 mins",
  },
  {
    name: "Theobroma",
    cloudinaryImageId: "b033728dcb0101ceb19bff0e1e1f6474",
    costForTwo: "₹400 for two",
    cuisines: ["Desserts"],
    avgRating: 4.6,
    slaString: "34 mins",
  },
  {
    name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
    cloudinaryImageId: "ihhogbpgpudzvikwmzjg",
    costForTwo: "₹100 for two",
    cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
    avgRating: 4.5,
    slaString: "36 mins",
  },
  {
    name: "KFC",
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    avgRating: 4.2,
    slaString: "37 mins",
  },
  {
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 4.0,
    slaString: "55 mins",
  },
  {
    name: "Burger King",
    cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "American"],
    avgRating: 4.2,
    slaString: "55 mins",
  },
  {
    name: "Oven Story Pizza - Standout Toppings",
    cloudinaryImageId: "f986df6f1a1fcf2ff24d2eaf44d570a7",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
    avgRating: 4.1,
    slaString: "23-28 mins",
  },
  {
    name: "Istah - The Mediterranean Way",
    cloudinaryImageId: "9a01f2935fcb5ae05426db8264062102",
    costForTwo: "₹250 for two",
    cuisines: [
      "Mediterranean",
      "Snacks",
      "Biryani",
      "Grill",
      "Kebabs",
      "Arabian",
      "Lebanese",
      "Beverages",
      "Desserts",
      "Italian",
      "Turkish",
    ],
    avgRating: 4.3,
    slaString: "55 mins",
  },
  {
    name: "NIC Ice Creams",
    cloudinaryImageId: "85825a6d74b1059a63a9b688de9f67ce",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.5,
    slaString: "35 mins",
  },
  {
    name: "Subway",
    cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4.1,
    slaString: "49 mins",
  },
  {
    name: "Pista House Bakery",
    cloudinaryImageId: "6a02cee5c367c438ec8a4becf0b98b1c",
    costForTwo: "₹500 for two",
    cuisines: ["Indian", "Bakery"],
    avgRating: 4.4,
    slaString: "20 mins",
  },
  {
    name: "Pista House Restaurant & Bakery",
    cloudinaryImageId: "gztlag7iu5911juzggqz",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Biryani", "Tandoor", "Chinese"],
    avgRating: 4.3,
    slaString: "27 mins",
  },
  {
    name: "Mehfil",
    cloudinaryImageId: "esp0fhddgfgdss5hyhpi",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "North Indian", "Tandoor", "Chinese", "Kebabs"],
    avgRating: 4.1,
    slaString: "14 mins",
  },
  {
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
    costForTwo: "₹300 for two",
    cuisines: [
      "Burgers",
      "American",
      "Turkish",
      "Portuguese",
      "Continental",
      "Snacks",
    ],
    avgRating: 4.3,
    slaString: "17 mins",
  },
  {
    name: "Subbayya Gari Hotel",
    cloudinaryImageId: "wnln2kbetcoxacsj8kao",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian", "Andhra", "Sweets"],
    avgRating: 4.1,
    slaString: "22 mins",
  },
  {
    name: "Shah Ghouse Hotel & Restaurant",
    cloudinaryImageId: "bk26jkkqpg55veii0aj9",
    costForTwo: "₹350 for two",
    cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai", "North Indian"],
    avgRating: 4.2,
    slaString: "25 mins",
  },
  {
    name: "McDonald's",
    cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: 4.3,
    slaString: "16 mins",
  },
];

export default restList;
